image: htfy96/build-image

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - buildandtest

.build_template: &build_definition
    stage: buildandtest
    tags:
        - docker
    script:
        - mkdir -p build && cd build && rm -rf *
        - cmake -DCMAKE_BUILD_TYPE=Release -Dstatic_map-build_tests=ON -DCMAKE_C_COMPILER=${X_CC} -DCMAKE_CXX_COMPILER=${X_CXX} ..
        - make VERBOSE=1
        - ctest --output-on-failure
    artifacts:
        paths:
            - build/
        when: on_failure


build-gcc5:
    <<: *build_definition
    variables:
        X_CXX: g++-5
        X_CC: gcc-5

build-gcc6:
    <<: *build_definition
    variables:
        X_CXX: g++-6
        X_CC: gcc-6

build-clang3.8:
    <<: *build_definition
    variables:
        X_CXX: clang++-3.8
        X_CC: clang-3.8

build-clang3.9:
    <<: *build_definition
    variables:
        X_CXX: clang++-3.9
        X_CC: clang-3.9
