image: htfy96/build-image

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - buildandtest

.build_template: &build_definition
    stage: buildandtest
    tags:
        - docker
    script:
        - ${X_CXX} -std=c++14 -O3 -o static_map static_map.cpp
        - ./print-func-asm.sh static_map 'test_1\(\)' | ./check-optimized.sh
        - ./print-func-asm.sh static_map 'test_2\(\)' | ./check-optimized.sh
        - ./static_map
    artifacts:
        paths:
            - ./static_map
        when: on_failure


build-gcc5:
    <<: *build_definition
    variables:
        X_CXX: g++-5

build-gcc6:
    <<: *build_definition
    variables:
        X_CXX: g++-6

build-clang3.8:
    <<: *build_definition
    variables:
        X_CXX: clang++-3.8

build-clang3.9:
    <<: *build_definition
    variables:
        X_CXX: clang++-3.9
